language: php
php:
  - 5.4
  - 5.5
  - 5.6

install:
  - travis_retry composer self-update && composer --version
  - travis_retry composer global require "fxp/composer-asset-plugin:1.0.0"
  - travis_retry composer install --prefer-dist --no-interaction
